// Flash attention vec kernel instantiations for tq_uniform_4b key type
#ifdef LLAMA_TURBOQUANT

#include "../fattn-vec.cuh"

// K=tq_uniform_4b, V=F16
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_F16);

// K=tq_uniform_4b, V=Q4_0
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q4_0);

// K=tq_uniform_4b, V=Q8_0
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q8_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_Q8_0);

// K=tq_uniform_4b, V=BF16
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_BF16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_BF16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ_UNIFORM_4B, GGML_TYPE_BF16);

#endif // LLAMA_TURBOQUANT
